require('barbar').setup()

vim.keymap.set('n', '<A-1>', '<Cmd>BufferGoto 1<CR>', {noremap = true, silent = true})
vim.keymap.set('n', '<A-2>', '<Cmd>BufferGoto 2<CR>', {noremap = true, silent = true})
vim.keymap.set('n', '<A-3>', '<Cmd>BufferGoto 3<CR>', {noremap = true, silent = true})
vim.keymap.set('n', '<A-4>', '<Cmd>BufferGoto 4<CR>', {noremap = true, silent = true})
vim.keymap.set('n', '<A-5>', '<Cmd>BufferGoto 5<CR>', {noremap = true, silent = true})
vim.keymap.set('n', '<A-6>', '<Cmd>BufferGoto 6<CR>', {noremap = true, silent = true})
vim.keymap.set('n', '<A-7>', '<Cmd>BufferGoto 7<CR>', {noremap = true, silent = true})
vim.keymap.set('n', '<A-8>', '<Cmd>BufferGoto 8<CR>', {noremap = true, silent = true})
vim.keymap.set('n', '<A-9>', '<Cmd>BufferGoto 9<CR>', {noremap = true, silent = true})
vim.keymap.set('n', '<A-0>', '<Cmd>BufferLast<CR>', {noremap = true, silent = true})
vim.keymap.set('n', '<A-w>', '<Cmd>BufferClose<CR>', {noremap = true, silent = true})
vim.keymap.set('n', '<A-S-w>', '<Cmd>BufferRestore<CR>', {noremap = true, silent = true})
